apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: APPSODY_PROJECT_NAME
spec:
  # Add fields here
  version: 1.0.0
  applicationImage: APPSODY_DOCKER_IMAGE 
  stack: APPSODY_STACK
  service:
    type: NodePort
    port: APPSODY_PORT
  env:
    - name: KAFKA_BROKERS
      valueFrom:
        configMapKeyRef:
          key: brokers
          name: kafka-brokers
    - name: KAFKA_APIKEY
      valueFrom:
        secretKeyRef:
          key: binding
          name: es-cp4i-apikey
          optional: true
    - name: SSL_ENABLED
      value: "true"
    - name: CERT_LOCATION
      value: /deployments/truststore.jks
    livenessProbe:
      failureThreshold: 12
      httpGet:
        path: /health/live
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 2
    readinessProbe:
      failureThreshold: 12
      httpGet:
        path: /health/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 2
      timeoutSeconds: 1
  monitoring:
    labels:
      k8s-app: APPSODY_PROJECT_NAME
  expose: true
