apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: APPSODY_PROJECT_NAME
spec:
  # Add fields here
  version: 1.0.0
  applicationImage: APPSODY_DOCKER_IMAGE 
  stack: APPSODY_STACK
  service:
    type: NodePort
    port: APPSODY_PORT
  env:
    - name: KAFKA_BROKERS
      valueFrom:
        configMapKeyRef:
          key: brokers
          name: kafka-brokers
    - name: KAFKA_USER
      valueFrom:
        configMapKeyRef:
          key: user
          name: kafka-brokers
    - name: KAFKA_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: es-user-secret
    - name: KAFKA_CERT_PATH
      value: /deployments/certs/ca.p12
    - name: KAFKA_CERT_PWD
      valueFrom:
        secretKeyRef:
          key: ca.password
          name: es-cluster-ca-cert
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  monitoring:
    labels:
      k8s-app: APPSODY_PROJECT_NAME
  expose: true
  volumeMounts:
  - mountPath: /deployments/certs/ca.p12
    name: es-cert
    readOnly: true
    subPath: ca.p12
  volumes:
  - name: es-cert
    secret:
      secretName: es-cluster-ca-cert
