name: IBM_GSE_EDA_Quarkus
version: 1.7.1
description: Quarkus 1.7.1 runtime for running Java applications, kafka 2.5, Event Streams 10
license: Apache-2.0
language: java
maintainers:
  - name: jerome boyer
    email: boyerje@us.ibm.com
    githuo-id: ibm-cloud-architecture 
default-template: kafka
requirements:
   appsody-version: ">= 0.6.0"
